<?php

// Modernized config array format
return [
    'pathmain' => 'dirname(__FILE__)/',
    'pathfonts' => '$k_path_main/fonts/',
    'pathurl' => '$k_path_url',
    'pathimages' => '$tcpdf_images_path',
    'headerlogo' => '$tcpdf_header_logo',
    'headerlogowidth' => 0,
    'pathcache' => '$K_PATH_CACHE',
    'blankimage' => '_blank.png',
    'pageformat' => 'A4',
    'pageorientation' => 'P',
    'creator' => 'TCPDF',
    'author' => 'TCPDF',
    'headertitle' => 'TCPDF Example',
    'headerstring' => "dude by Nicola Asuni - Tecnick.com\nwww.tcpdf.org",
    'unit' => 'mm',
    'marginheader' => 5,
    'marginfooter' => 10,
    'margintop' => 27,
    'marginbottom' => 25,
    'marginleft' => 15,
    'marginright' => 15,
    'fontnamemain' => 'helvetica',
    'fontsizemain' => 10,
    'fontnamedata' => 'helvetica',
    'fontsizedata' => 8,
    'fontmonospaced' => 'courier',
    'imagescaleratio' => 1.25,
    'headmagnification' => 1.1,
    'cellheightratio' => 1.25,
    'titlemagnification' => 1.3,
    'smallratio' => '2/3',
    'thaitopchars' => true,
    'tcpdfcallsinhtml' => false,
    'allowedtcpdftags' => '',
    'tcpdfthrowexceptionerror' => false,
    'timezone' => '@date_default_timezone_get()',
    'curlopts' => 'array()',
];
