<?php

/**
 * limePDF Properties Configuration
 * Auto-generated on 2025-07-21 13:50:35
 * Contains 246 properties extracted from TCPDF
 */
class limePDFProperties
{
    /**
     * Get all default property values
     * @return array
     */
    public static function getDefaultProperties(): array
    {
        return [
            'AutoPageBreak' => NULL,
            'ColorFlag' => NULL,
            'CoreFonts' => NULL,
            'CurOrientation' => NULL,
            'CurrentFont' => NULL,
            'DrawColor' => NULL,
            'FillColor' => NULL,
            'FontAscent' => NULL,
            'FontDescent' => NULL,
            'FontFamily' => NULL,
            'FontFiles' => array(
),
            'FontSize' => NULL,
            'FontSizePt' => NULL,
            'FontStyle' => NULL,
            'HREF' => array(
),
            'InFooter' => false,
            'InHeader' => false,
            'LayoutMode' => NULL,
            'LineWidth' => NULL,
            'OutlineRoot' => NULL,
            'PDFVersion' => '1.7',
            'PageAnnots' => array(
),
            'PageBreakTrigger' => NULL,
            'PageMode' => NULL,
            'TextColor' => NULL,
            'ZoomMode' => NULL,
            'allowLocalFiles' => false,
            'alpha' => array(
                0 => '\'CA\' => 1',
                1 => '\'ca\' => 1',
                2 => 'BM\' => \'/Normal',
                3 => '\'AIS\' => false',
),
            'annotation_fonts' => array(
),
            'author' => '',
            'bMargin' => NULL,
            'barcode' => false,
            'bgcolor' => NULL,
            'booklet' => false,
            'bordermrk' => array(
),
            'buffer' => NULL,
            'bufferlen' => 0,
            'cache_file_length' => array(
),
            'cell_height_ratio' => 'K_CELL_HEIGHT_RATIO',
            'cell_margin' => array(
                0 => '\'T\' => 0',
                1 => '\'R\' => 0',
                2 => '\'B\' => 0',
                3 => '\'L\' => 0',
),
            'cell_padding' => array(
                0 => '\'T\' => 0',
                1 => '\'R\' => 0',
                2 => '\'B\' => 0',
                3 => '\'L\' => 0',
),
            'check_page_regions' => true,
            'clMargin' => NULL,
            'cntmrk' => array(
),
            'column_start_page' => 0,
            'columns' => array(
),
            'colxshift' => array(
                0 => '\'x\' => 0',
                1 => '\'s\' => array(\'H\' => 0',
                2 => '\'V\' => 0)',
                3 => '\'p\' => array(\'L\' => 0',
                4 => '\'T\' => 0',
                5 => '\'R\' => 0',
                6 => '\'B\' => 0)',
),
            'compress' => NULL,
            'crMargin' => NULL,
            'creator' => '',
            'current_column' => 0,
            'currpagegroup' => 0,
            'custom_xmp' => '',
            'custom_xmp_rdf' => '',
            'custom_xmp_rdf_pdfaExtension' => '',
            'customlistindent' => -1,
            'default_form_prop' => array(
                0 => '\'lineWidth\'=>1',
                1 => 'borderStyle\'=>\'solid',
                2 => '\'fillColor\'=>array(255',
                3 => 255,
                4 => '255)',
                5 => '\'strokeColor\'=>array(128',
                6 => 128,
                7 => '128)',
),
            'default_graphic_vars' => array(
),
            'default_monospaced_font' => 'courier',
            'default_table_columns' => 4,
            'dests' => array(
),
            'diffs' => array(
),
            'doc_creation_timestamp' => NULL,
            'doc_modification_timestamp' => NULL,
            'docinfounicode' => true,
            'dpi' => 72,
            'efnames' => array(
),
            'embeddedfiles' => array(
),
            'empty_signature_appearance' => array(
),
            'emptypagemrk' => array(
),
            'encoding' => 'UTF-8',
            'encryptdata' => array(
),
            'encrypted' => NULL,
            'endlinex' => 0,
            'epsmarker' => 'x#!#EPS#!#x',
            'extgstates' => NULL,
            'feps' => 0.005,
            'fgcolor' => NULL,
            'fhPt' => NULL,
            'fileContentCache' => array(
),
            'file_id' => NULL,
            'font_obj_ids' => array(
),
            'font_spacing' => 0,
            'font_stretching' => 100,
            'font_subsetting' => true,
            'fontkeys' => array(
),
            'fontlist' => array(
),
            'fonts' => array(
),
            'footer_font' => NULL,
            'footer_line_color' => array(
                0 => 0,
                1 => 0,
                2 => 0,
),
            'footer_margin' => NULL,
            'footer_text_color' => array(
                0 => 0,
                1 => 0,
                2 => 0,
),
            'footerlen' => array(
),
            'footerpos' => array(
),
            'force_srgb' => false,
            'form_action' => '',
            'form_enctype' => 'application/x-www-form-urlencoded',
            'form_mode' => 'post',
            'form_obj_id' => array(
),
            'fwPt' => NULL,
            'gdgammacache' => array(
),
            'gradients' => array(
),
            'h' => NULL,
            'hPt' => NULL,
            'hash_key' => NULL,
            'header_font' => NULL,
            'header_line_color' => array(
                0 => 0,
                1 => 0,
                2 => 0,
),
            'header_logo' => '',
            'header_logo_width' => 30,
            'header_margin' => NULL,
            'header_string' => '',
            'header_text_color' => array(
                0 => 0,
                1 => 0,
                2 => 0,
),
            'header_title' => '',
            'header_xobj_autoreset' => false,
            'header_xobjid' => false,
            'htmlLinkColorArray' => array(
                0 => 0,
                1 => 0,
                2 => 255,
),
            'htmlLinkFontStyle' => 'U',
            'htmlvspace' => 0,
            'imagekeys' => array(
),
            'images' => array(
),
            'img_rb_x' => NULL,
            'img_rb_y' => NULL,
            'imgscale' => 1,
            'inthead' => false,
            'intmrk' => array(
),
            'inxobj' => false,
            'isunicode' => false,
            'javascript' => '',
            'jpeg_quality' => NULL,
            'js_objects' => array(
),
            'k' => NULL,
            'keywords' => '',
            'l' => NULL,
            'lMargin' => NULL,
            'last_enc_key' => NULL,
            'last_enc_key_c' => NULL,
            'lasth' => NULL,
            'linestyleCap' => '0 J',
            'linestyleDash' => '[] 0 d',
            'linestyleJoin' => '0 j',
            'linestyleWidth' => '',
            'linethrough' => NULL,
            'links' => array(
),
            'lispacer' => '',
            'listcount' => array(
),
            'listindent' => 0,
            'listindentlevel' => 0,
            'listnum' => 0,
            'listordered' => array(
),
            'lisymbol' => '',
            'maxselcol' => array(
                0 => '\'page\' => 0',
                1 => '\'column\' => 0',
),
            'n' => NULL,
            'n_dests' => NULL,
            'n_js' => NULL,
            'newline' => true,
            'newpagegroup' => array(
),
            'num_columns' => 1,
            'numfonts' => 0,
            'numimages' => 0,
            'numpages' => 0,
            'objcopy' => NULL,
            'offsets' => array(
),
            'openMarkedContent' => false,
            'opencell' => true,
            'original_lMargin' => NULL,
            'original_rMargin' => NULL,
            'outlines' => array(
),
            'overline' => NULL,
            'overprint' => array(
                0 => '\'OP\' => false',
                1 => '\'op\' => false',
                2 => '\'OPM\' => 0',
),
            'page' => NULL,
            'page_boxes' => array(
                0 => 'MediaBox',
                1 => 'CropBox',
                2 => 'BleedBox',
                3 => 'TrimBox',
                4 => 'ArtBox',
),
            'page_obj_id' => array(
),
            'page_regions' => array(
),
            'pagedim' => array(
),
            'pagegroups' => array(
),
            'pagelen' => array(
),
            'pageobjects' => array(
),
            'pageopen' => array(
),
            'pages' => array(
),
            'pdfa_mode' => false,
            'pdfa_version' => 1,
            'pdflayers' => array(
),
            'pdfunit' => 'mm',
            'premode' => false,
            'print_footer' => true,
            'print_header' => true,
            'rMargin' => NULL,
            'radio_groups' => array(
),
            'radiobutton_groups' => array(
),
            'rasterize_vector_images' => false,
            're_space' => array(
                0 => 'p\' => \'[^\\S\\xa0]',
                1 => 'm\' => \'',
),
            're_spaces' => '/[^\\S\\xa0]/',
            'rtl' => false,
            'sig_obj_id' => 0,
            'sign' => false,
            'signature_appearance' => array(
                0 => '\'page\' => 1',
                1 => 'rect\' => \'0 0 0 0',
),
            'signature_data' => array(
),
            'signature_max_length' => 11742,
            'spot_colors' => array(
),
            'start_transaction_page' => 0,
            'start_transaction_y' => 0,
            'starting_page_number' => 1,
            'state' => NULL,
            'strokecolor' => NULL,
            'subject' => '',
            'svg_tag_depth' => 0,
            'svgclipid' => 0,
            'svgclipmode' => false,
            'svgclippaths' => array(
),
            'svgcliptm' => array(
),
            'svgdefs' => array(
),
            'svgdefsmode' => false,
            'svgdir' => '',
            'svggradientid' => 0,
            'svggradients' => array(
),
            'svgstyles' => array(
                0 => 'array(
                        \'alignment-baseline\' => \'auto\'',
                1 => 'baseline-shift\' => \'baseline',
                2 => 'clip\' => \'auto',
                3 => 'clip-path\' => \'none',
                4 => 'clip-rule\' => \'nonzero',
                5 => 'color\' => \'black',
                6 => 'color-interpolation\' => \'sRGB',
                7 => 'color-interpolation-filters\' => \'linearRGB',
                8 => 'color-profile\' => \'auto',
                9 => 'color-rendering\' => \'auto',
                10 => 'cursor\' => \'auto',
                11 => 'direction\' => \'ltr',
                12 => 'display\' => \'inline',
                13 => 'dominant-baseline\' => \'auto',
                14 => 'enable-background\' => \'accumulate',
                15 => 'fill\' => \'black',
                16 => '\'fill-opacity\' => 1',
                17 => 'fill-rule\' => \'nonzero',
                18 => 'filter\' => \'none',
                19 => 'flood-color\' => \'black',
                20 => '\'flood-opacity\' => 1',
                21 => 'font\' => \'',
                22 => 'font-family\' => \'helvetica',
                23 => 'font-size\' => \'medium',
                24 => 'font-size-adjust\' => \'none',
                25 => 'font-stretch\' => \'normal',
                26 => 'font-style\' => \'normal',
                27 => 'font-variant\' => \'normal',
                28 => 'font-weight\' => \'normal',
                29 => 'glyph-orientation-horizontal\' => \'0deg',
                30 => 'glyph-orientation-vertical\' => \'auto',
                31 => 'image-rendering\' => \'auto',
                32 => 'kerning\' => \'auto',
                33 => 'letter-spacing\' => \'normal',
                34 => 'lighting-color\' => \'white',
                35 => 'marker\' => \'',
                36 => 'marker-end\' => \'none',
                37 => 'marker-mid\' => \'none',
                38 => 'marker-start\' => \'none',
                39 => 'mask\' => \'none',
                40 => '\'opacity\' => 1',
                41 => 'overflow\' => \'auto',
                42 => 'pointer-events\' => \'visiblePainted',
                43 => 'shape-rendering\' => \'auto',
                44 => 'stop-color\' => \'black',
                45 => '\'stop-opacity\' => 1',
                46 => 'stroke\' => \'none',
                47 => 'stroke-dasharray\' => \'none',
                48 => '\'stroke-dashoffset\' => 0',
                49 => 'stroke-linecap\' => \'butt',
                50 => 'stroke-linejoin\' => \'miter',
                51 => '\'stroke-miterlimit\' => 4',
                52 => '\'stroke-opacity\' => 1',
                53 => '\'stroke-width\' => 1',
                54 => 'text-anchor\' => \'start',
                55 => 'text-decoration\' => \'none',
                56 => 'text-rendering\' => \'auto',
                57 => 'unicode-bidi\' => \'normal',
                58 => 'visibility\' => \'visible',
                59 => 'word-spacing\' => \'normal',
                60 => 'writing-mode\' => \'lr-tb',
                61 => 'text-color\' => \'black',
                62 => '\'transfmatrix\' => array(1',
                63 => 0,
                64 => 0,
                65 => 1,
                66 => 0,
                67 => '0)
                        )',
),
            'svgtext' => '',
            'svgtextmode' => array(
),
            'svgunit' => 'px',
            'tMargin' => NULL,
            'tagvspaces' => array(
),
            'tcpdflink' => true,
            'tempfontsize' => 10,
            'textindent' => 0,
            'textrendermode' => 0,
            'textstrokewidth' => 0,
            'thead' => '',
            'theadMargins' => array(
),
            'title' => '',
            'tmprtl' => false,
            'tocpage' => false,
            'transfmatrix' => array(
),
            'transfmatrix_key' => 0,
            'transfmrk' => array(
),
            'tsa_data' => array(
),
            'tsa_timestamp' => false,
            'txtshadow' => array(
                0 => '\'enabled\'=>false',
                1 => '\'depth_w\'=>0',
                2 => '\'depth_h\'=>0',
                3 => '\'color\'=>false',
                4 => '\'opacity\'=>1',
                5 => 'blend_mode\'=>\'Normal',
),
            'underline' => NULL,
            'ur' => array(
),
            'viewer_preferences' => NULL,
            'w' => NULL,
            'wPt' => NULL,
            'x' => NULL,
            'xobjects' => array(
),
            'xobjid' => '',
            'y' => NULL,
        ];
    }

    /**
     * Get property groups for organized access
     * @return array
     */
    public static function getPropertyGroups(): array
    {
        return [
            'core' => [
                'buffer',
                'n',
                'offsets',
                'page',
                'state',
            ],
            'page' => [
                'AutoPageBreak',
                'PageAnnots',
                'PageBreakTrigger',
                'PageMode',
                'check_page_regions',
                'column_start_page',
                'currpagegroup',
                'emptypagemrk',
                'newpagegroup',
                'numpages',
                'page_boxes',
                'page_obj_id',
                'page_regions',
                'pagedim',
                'pagegroups',
                'pagelen',
                'pageobjects',
                'pageopen',
                'pages',
                'start_transaction_page',
                'starting_page_number',
                'tocpage',
            ],
            'font' => [
                'CoreFonts',
                'CurrentFont',
                'FontAscent',
                'FontDescent',
                'FontFamily',
                'FontFiles',
                'FontSize',
                'FontSizePt',
                'FontStyle',
                'annotation_fonts',
                'default_monospaced_font',
                'font_obj_ids',
                'font_spacing',
                'font_stretching',
                'font_subsetting',
                'fontkeys',
                'fontlist',
                'fonts',
                'footer_font',
                'header_font',
                'htmlLinkFontStyle',
                'numfonts',
                'tempfontsize',
            ],
            'color' => [
                'ColorFlag',
                'DrawColor',
                'FillColor',
                'TextColor',
                'bgcolor',
                'fgcolor',
                'footer_line_color',
                'footer_text_color',
                'header_line_color',
                'header_text_color',
                'htmlLinkColorArray',
                'spot_colors',
                'strokecolor',
            ],
            'image' => [
                'imagekeys',
                'images',
                'img_rb_x',
                'img_rb_y',
                'imgscale',
                'numimages',
                'rasterize_vector_images',
            ],
            'header' => [
                'InHeader',
                'header_logo',
                'header_logo_width',
                'header_margin',
                'header_string',
                'header_title',
                'header_xobj_autoreset',
                'header_xobjid',
                'print_header',
            ],
            'footer' => [
                'InFooter',
                'footer_margin',
                'footerlen',
                'footerpos',
                'print_footer',
            ],
            'margin' => [
                'bMargin',
                'cell_margin',
                'clMargin',
                'crMargin',
                'lMargin',
                'original_lMargin',
                'original_rMargin',
                'rMargin',
                'tMargin',
                'theadMargins',
            ],
            'border' => [
                'bordermrk',
            ],
            'cell' => [
                'cell_height_ratio',
                'cell_padding',
                'opencell',
            ],
            'link' => [
                'links',
                'tcpdflink',
            ],
            'javascript' => [
                'javascript',
                'js_objects',
                'n_js',
            ],
            'form' => [
                'default_form_prop',
                'form_action',
                'form_enctype',
                'form_mode',
                'form_obj_id',
            ],
            'security' => [
                'encryptdata',
                'encrypted',
            ],
            'metadata' => [
                'author',
                'title',
            ],
            'other' => [
                'CurOrientation',
                'HREF',
                'LayoutMode',
                'LineWidth',
                'OutlineRoot',
                'PDFVersion',
                'ZoomMode',
                'allowLocalFiles',
                'alpha',
                'barcode',
                'booklet',
                'bufferlen',
                'cache_file_length',
                'cntmrk',
                'columns',
                'colxshift',
                'compress',
                'creator',
                'current_column',
                'custom_xmp',
                'custom_xmp_rdf',
                'custom_xmp_rdf_pdfaExtension',
                'customlistindent',
                'default_graphic_vars',
                'default_table_columns',
                'dests',
                'diffs',
                'doc_creation_timestamp',
                'doc_modification_timestamp',
                'docinfounicode',
                'dpi',
                'efnames',
                'embeddedfiles',
                'empty_signature_appearance',
                'encoding',
                'endlinex',
                'epsmarker',
                'extgstates',
                'feps',
                'fhPt',
                'fileContentCache',
                'file_id',
                'force_srgb',
                'fwPt',
                'gdgammacache',
                'gradients',
                'h',
                'hPt',
                'hash_key',
                'htmlvspace',
                'inthead',
                'intmrk',
                'inxobj',
                'isunicode',
                'jpeg_quality',
                'k',
                'keywords',
                'l',
                'last_enc_key',
                'last_enc_key_c',
                'lasth',
                'linestyleCap',
                'linestyleDash',
                'linestyleJoin',
                'linestyleWidth',
                'linethrough',
                'lispacer',
                'listcount',
                'listindent',
                'listindentlevel',
                'listnum',
                'listordered',
                'lisymbol',
                'maxselcol',
                'n_dests',
                'newline',
                'num_columns',
                'objcopy',
                'openMarkedContent',
                'outlines',
                'overline',
                'overprint',
                'pdfa_mode',
                'pdfa_version',
                'pdflayers',
                'pdfunit',
                'premode',
                'radio_groups',
                'radiobutton_groups',
                're_space',
                're_spaces',
                'rtl',
                'sig_obj_id',
                'sign',
                'signature_appearance',
                'signature_data',
                'signature_max_length',
                'start_transaction_y',
                'subject',
                'svg_tag_depth',
                'svgclipid',
                'svgclipmode',
                'svgclippaths',
                'svgcliptm',
                'svgdefs',
                'svgdefsmode',
                'svgdir',
                'svggradientid',
                'svggradients',
                'svgstyles',
                'svgtext',
                'svgtextmode',
                'svgunit',
                'tagvspaces',
                'textindent',
                'textrendermode',
                'textstrokewidth',
                'thead',
                'tmprtl',
                'transfmatrix',
                'transfmatrix_key',
                'transfmrk',
                'tsa_data',
                'tsa_timestamp',
                'txtshadow',
                'underline',
                'ur',
                'viewer_preferences',
                'w',
                'wPt',
                'x',
                'xobjects',
                'xobjid',
                'y',
            ],
        ];
    }
}
